### ISSUE TITLE
Unable to use Tyxia 5650

### ISSUE THREAD

**Issue by moi952** [tydom2mqtt/tydom2mqtt#228]
When I change the intensity of my lights via the physical push button I can see the status of my lighting in Home assistant, however if I want to turn my light on or off via Home assistant I get an error in the tydom2mqtt logs.

The message is : 
light/tydom/1734101151_1734101151/set_level
QoS: 0
Payload: 43

Here is the error I get.

If you need more information I am available.

Thank you very much for your work.

date | stream | content
-- | -- | --
2024/12/13 19:14:41 | stdout | TypeError: Light.put_level() got an unexpected keyword argument 'cover_id'
2024/12/13 19:14:41 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/13 19:14:41 | stdout | await Light.put_level(tydom_client=self.tydom, device_id=device_id, cover_id=endpoint_id,
2024/12/13 19:14:41 | stdout | File "/app/mqtt/MqttClient.py", line 202, in on_message
2024/12/13 19:14:41 | stdout | Traceback (most recent call last):
2024/12/13 19:14:41 | stdout | future: <Task finished name='Task-147' coro=<MqttClient.on_message() done, defined at /app/mqtt/MqttClient.py:79> exception=TypeError("Light.put_level() got an unexpected keyword argument 'cover_id'")>
2024/12/13 19:14:41 | stdout | 2024-12-13 18:14:41,215 - asyncio              - ERROR   - Task exception was never retrieved
2024/12/13 19:14:41 | stdout | 2024-12-13 18:14:41,214 - mqtt.MqttClient      - INFO    - set_level message received (topic=light/tydom/1734101151_1734101151/set_level, message=43)
2024/12/13 19:14:09 | stdout | )
2024/12/13 19:14:09 | stdout | 2024-12-13 18:14:09,819 - tydom.MessageHandler - WARNING - Unknown message type received ([]

**Comment by moi952** [comment]
> When I change the intensity of my lights via the physical push button I can see the status of my lighting in Home assistant, however if I want to turn my light on or off via Home assistant I get an error in the tydom2mqtt logs.

The sent message is : 
light/tydom/1734101151_1734101151/set_level
QoS: 0
Payload: 9
> 
> Here is the error I get.
> 
> If you need more information I am available.
> 
> Thank you very much for your work.
> 
> date	stream	content
> 2024/12/13 19:14:41	stdout	TypeError: Light.put_level() got an unexpected keyword argument 'cover_id'
> 2024/12/13 19:14:41	stdout	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024/12/13 19:14:41	stdout	await Light.put_level(tydom_client=self.tydom, device_id=device_id, cover_id=endpoint_id,
> 2024/12/13 19:14:41	stdout	File "/app/mqtt/MqttClient.py", line 202, in on_message
> 2024/12/13 19:14:41	stdout	Traceback (most recent call last):
> 2024/12/13 19:14:41	stdout	future: <Task finished name='Task-147' coro=<MqttClient.on_message() done, defined at /app/mqtt/MqttClient.py:79> exception=TypeError("Light.put_level() got an unexpected keyword argument 'cover_id'")>
> 2024/12/13 19:14:41	stdout	2024-12-13 18:14:41,215 - asyncio              - ERROR   - Task exception was never retrieved
> 2024/12/13 19:14:41	stdout	2024-12-13 18:14:41,214 - mqtt.MqttClient      - INFO    - set_level message received (topic=light/tydom/1734101151_1734101151/set_level, message=43)
> 2024/12/13 19:14:09	stdout	)
> 2024/12/13 19:14:09	stdout	2024-12-13 18:14:09,819 - tydom.MessageHandler - WARNING - Unknown message type received ([]

**Comment by Mips2648** [comment]
Hi,
If you are using the docker image, which seems to be the case, you should update to 3.5.3: https://hub.docker.com/r/fmartinou/tydom2mqtt/tags

The "latest" image tag is not actually the latest (6 months ago) and wasn't updated with the last version of tydom2mqtt which fix this issue: https://github.com/tydom2mqtt/tydom2mqtt/releases/tag/3.5.3 (3 months ago)

**Comment by moi952** [comment]
Thank you very much, that fixed the problem, too bad the tag is not good.
It would be great if 3.5.3 had the "latest" tag

**Comment by BlacKTM1190** [comment]
Hello
We're aware that "latest" tag is not pointing 3.5.3 as it was mentioned in #221.
We're currently restructuring the repo, sry for the delay...
However, could you give us the reference of your dimable modules ?

**Comment by moi952** [comment]
@BlacKTM1190 Thanks for your reply, I use the Tyxia 5650 and it solved my problem :)

**Comment by BlacKTM1190** [comment]
Hello
NP ;)
I did notice the ref in the title after my last deleted post.
I personnally don't have dimmable lights modules so i thought it wasn't compatible.
We'll add to compatibility note.
Thanks @moi952
